# Generated by Django 3.1.1 on 2020-10-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=255)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('service_type_id', models.CharField(max_length=50)),
                ('service_type_name', models.CharField(blank=True, max_length=50)),
                ('service_category_id', models.CharField(max_length=50)),
                ('service_category_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Received'), (1, 'Pending'), (2, 'Completed')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-ordered_on'],
            },
        ),
    ]
