# Generated by Django 3.1.1 on 2020-09-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0010_auto_20200930_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img_path',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_video_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
