# Generated by Django 3.1.1 on 2020-09-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_blog', '0011_auto_20200930_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img_path',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_video_path',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
