# Generated by Django 3.1.1 on 2020-09-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0012_auto_20200930_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img_path',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_video_path',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
