# Generated by Django 3.1.1 on 2020-09-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0016_auto_20200930_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_video_path',
            field=models.CharField(max_length=255),
        ),
    ]
