# Generated by Django 3.1.1 on 2020-09-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0017_auto_20200930_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_img_path',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_img_path',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image_path',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_image_path',
            field=models.ImageField(blank=True, upload_to='posts/thumbs/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_video_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
