# Generated by Django 3.1.1 on 2020-10-10 03:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
