# Generated by Django 3.1.1 on 2020-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201008_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/%Y%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_category_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
