# Generated by Django 3.1.1 on 2020-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_keywords', models.TextField()),
                ('meta_descriptions', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-meta_title'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(upload_to='settings')),
                ('favicon', models.ImageField(upload_to='settings')),
                ('email', models.EmailField(max_length=255)),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('contact_number1', models.CharField(max_length=50)),
                ('contact_number2', models.CharField(blank=True, max_length=50)),
                ('copyright_text', models.CharField(max_length=255)),
                ('map_iframe_script', models.TextField(blank=True)),
                ('google_analytics_script', models.TextField(blank=True)),
                ('custom_header_script', models.TextField(blank=True)),
                ('custom_footer_script', models.TextField(blank=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255)),
                ('twitter_url', models.CharField(blank=True, max_length=255)),
                ('instagram_url', models.CharField(blank=True, max_length=255)),
                ('youtube_url', models.CharField(blank=True, max_length=255)),
                ('use_https', models.BooleanField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Under Maintainance')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-brand_name'],
            },
        ),
    ]
