# Generated by Django 3.1.1 on 2020-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='google_analytics_appid',
            field=models.TextField(blank=True),
        ),
    ]
