# Generated by Django 3.1.1 on 2020-10-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_settings', '0002_setting_google_analytics_appid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='google_analytics_appid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
