# Generated by Django 3.1.1 on 2020-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0002_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img_path',
            field=models.ImageField(upload_to='posts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img_path',
            field=models.ImageField(blank=True, upload_to='posts/thumbs/%Y/%m/%d'),
        ),
    ]
