# Generated by Django 3.1.1 on 2020-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0018_auto_20200930_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image_path',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d%H/%M/%S'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb_image_path',
            field=models.ImageField(blank=True, upload_to='posts/thumbs/%Y/%m/%d%H/%M/%S'),
        ),
    ]
