# Generated by Django 3.1.1 on 2020-09-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('cover_image_path', models.ImageField(upload_to='services/%Y/%m/%d')),
                ('thumb_image_path', models.ImageField(upload_to='services/thumbs/%Y/%m/%d')),
                ('minimum_visit_price', models.CharField(max_length=50)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicetype_to_services', to='everest_services.services')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_by', models.CharField(max_length=255)),
                ('reviewedby_name', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('reviewed_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_to_services', to='everest_services.services')),
            ],
            options={
                'ordering': ['-reviewed_on'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOfferings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceofferings_to_services', to='everest_services.services')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
