# Generated by Django 3.1.1 on 2020-09-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everest_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='ServiceCategories',
            new_name='ServiceCategory',
        ),
        migrations.RenameModel(
            old_name='ServiceOfferings',
            new_name='ServiceOffering',
        ),
        migrations.RenameModel(
            old_name='ServiceReviews',
            new_name='ServiceReview',
        ),
        migrations.RenameModel(
            old_name='ServiceTypes',
            new_name='ServiceType',
        ),
    ]
