# Generated by Django 3.1.1 on 2020-09-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everest_services', '0002_auto_20200930_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover_image_path',
            field=models.ImageField(blank=True, upload_to='services/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='thumb_image_path',
            field=models.ImageField(blank=True, upload_to='services/thumbs/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='category_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
