# Generated by Django 3.1.1 on 2020-10-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everest_services', '0004_auto_20201006_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='thumb_image_path',
            field=models.ImageField(blank=True, upload_to='services/thumbs'),
        ),
    ]
