# Generated by Django 3.1.1 on 2020-10-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everest_services', '0005_service_thumb_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pricing_image_path',
            field=models.ImageField(blank=True, upload_to='services/pricing'),
        ),
    ]
